### ISSUE TITLE
Error when trying to use the card

### ISSUE THREAD

**Issue by jamiekris** [isabellaalstrom/lovelace-pollenprognos-card#3]
Hi! Great work being done here, thanks first for that.

I have installed this card via HACS and find that the folder is available in 'www/community/lovelace-pollenprognos-card/'

When adding a new card on lovelace, I get this error 'Configuration errors detected: No type provided.'. I am using the exact example script on the readme, with the only change being to 'Norrköping'.

Can you please help :)

**Comment by isabellaalstrom** [comment]
There is probably a dash before type that shouldn't be there.

**Comment by jamiekris** [comment]
Hi! I tried to remove the dash and still keep the same indentation, it still complains the same error?

**Comment by isabellaalstrom** [comment]
You need to post what you are trying to do in code or at least screenshot for me to be able to help you. Also, are you in the gui or yaml files?

**Comment by jamiekris** [comment]
I'm using the exact lines as in the example in Readme in the yaml editor. See [https://mega.nz/file/TOYkhTRT#azQ6FwWGWrPTtnw2YFx4pVjgdrFNCC81qpKGo0Y5wlc](url) please.

**Comment by isabellaalstrom** [comment]
Sorry, the link isn't working for me. Why I want it is because it matters where you put the lines etc. The error message tells me it's most probably something to do with the config.

**Comment by jamiekris** [comment]
<img width="851" alt="Screenshot 2022-01-27 090200" src="https://user-images.githubusercontent.com/13977188/151316408-2deb219e-154d-4f6f-ab29-aa485e8a1c5d.png">

I hope this one works. I am using the exact same example code. Also tried to play with the dashes, but no luck really...

**Comment by isabellaalstrom** [comment]
Yeah, the example is for a whole view with the card in it. 

Remove everything and paste this
```
type: 'custom:pollenprognos-card'
title: false
city: Stockholm
allergens:
  - Al
  - Alm
  - Ambrosia
  - Björk
  - Ek
  - Gråbo
  - Gräs
  - Hassel
  - Sälg / vide
```

**Comment by jamiekris** [comment]
oh I see :) Thanks so much. Works now!
