### ISSUE TITLE
icon pack

### ISSUE THREAD

**Issue by kongo09** [isabellaalstrom/lovelace-pollenprognos-card#6]
Thanks for the great card. I would like to make this available for other pollen data as well. As a first step, I would like to create an icon pack from your wonderful icons to be used in Lovelace, installable via HACS.

Would that be ok for your? Obviously, I would link back to this place and give credit.

**Comment by isabellaalstrom** [comment]
The icons are from @TekniskSupport, who will look at this!

**Comment by TekniskSupport** [comment]
Thanks for the request @kongo09!

I see no issues with that, Knock yourself out.
Issue can be marked as resolved

**Comment by kongo09** [comment]
Thanks. Will report back here.
